apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: grafana
    server: '{{ .Values.spec.destination.server }}'
  ignoreDifferences:
    - group: apps
      jsonPointers:
        - /data/admin-password
      kind: Secret
    - group: apps
      jsonPointers:
        - /spec/template/metadata/annotations/checksum/secret
      kind: Deployment
  project: default
  source:
    chart: grafana
    helm:
      parameters:
        - name: service.type
          value: LoadBalancer
      valueFiles:
        - /grafana/values.yaml
    repoURL: https://grafana.github.io/helm-charts/
    targetRevision: 6.53.0
