apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: grafana
    server: '{{ .Values.spec.destination.server }}'
  project: default
  sources:
    - chart: grafana
      helm:
        parameters:
          - name: service.type
            value: LoadBalancer
        valueFiles:
          - "$values/grafana/values.yaml"
      repoURL: https://grafana.github.io/helm-charts/
      targetRevision: 6.53.0
    - ref: values
      repoURL: https://github.com/Preston4tw/koob.git
      # targetRevision: HEAD
