apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bme280
  namespace: bme280
spec:
  project: default
  source:
    repoURL: 'https://github.com/Preston4tw/bme280'
    path: k8s
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: bme280
