apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bme280
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Preston4tw/bme280'
    path: k8s
    targetRevision: HEAD
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: bme280
