apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: grafana
spec:
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts/'
    targetRevision: 6.32.15
    helm:
      parameters:
        - name: service.type
          value: LoadBalancer
    chart: grafana
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: grafana
