apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  project: default
  source:
    repoURL: 'https://k8s-at-home.com/charts/'
    targetRevision: 13.4.2
    helm:
      values: |-
        service:
          main:
            type: LoadBalancer
    chart: home-assistant
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: home-assistant
