{
 "title": "AirGradient",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esphome_sensor_value{id=\"temperature\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esphome_sensor_value{id=\"humidity\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esphome_sensor_value{id=\"senseair_co2_value\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "PM25",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esphome_sensor_value{id=\"particulate_matter_25m_concentration\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  { "title": "Now", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  { "title": "Historical", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "esphome_sensor_value{id=\"temperature\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "esphome_sensor_value{id=\"humidity\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "expr": "esphome_sensor_value{id=\"senseair_co2_value\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "PM25",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "expr": "esphome_sensor_value{id=\"particulate_matter_25m_concentration\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "esphome_sensor_value{id=\"uptime_sensor\"}",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}