apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: home-assistant
    app.kubernetes.io/name: home-assistant
  name: home-assistant
  namespace: home-assistant
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: home-assistant
      app.kubernetes.io/name: home-assistant
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: home-assistant
        app.kubernetes.io/name: home-assistant
    spec:
      automountServiceAccountToken: true
      containers:
        - env:
            - name: TZ
              value: UTC
          image: "ghcr.io/home-assistant/home-assistant:stable"
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 10
            tcpSocket:
              port: 8123
            timeoutSeconds: 1
          name: home-assistant
          ports:
            - containerPort: 8123
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 10
            tcpSocket:
              port: 8123
            timeoutSeconds: 1
          securityContext:
            privileged: null
          startupProbe:
            failureThreshold: 30
            initialDelaySeconds: 0
            periodSeconds: 5
            tcpSocket:
              port: 8123
            timeoutSeconds: 1
          volumeMounts:
            - name: home-assistant-vol
              mountPath: /config
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      serviceAccountName: default
      initContainers:
        # https://gist.github.com/tallclair/849601a16cebeee581ef2be50c351841
        - name: git-clone
          image: alpine/git
          args:
            - clone
            - --single-branch
            - --
            - https://github.com/Preston4tw/home-assistant.git
            - /repo
          securityContext:
            runAsUser: 65535 # non-root
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: home-assistant-vol
              mountPath: /repo
      volumes:
        - name: home-assistant-vol
          persistentVolumeClaim:
            claimName: home-assistant-pvc
